### ISSUE TITLE
[Member] 회비 승인 권한 변경

### ISSUE THREAD

**Issue by SWARVY** [kgu-clab/clab-platforms#222]
### 버그 설명

- `roleLevel`이 서버에서 정상적으로 리턴되어 권한을 가진 상태임에도 불구하고 승인 버튼이 출력되지 않는 문제 수정

### ETC

- 추가적으로 현재 하드코딩되어있는 `roleLevel` 관련 로직들의 경우 볼륨이 늘어나면 늘어날수록 해당 권한을 일괄적으로 수정할 때 문제가 생기므로, 해당 사항 상수로 분리하여 관리해야할듯 함

**Comment by gwansikk** [comment]
- #221

해당 PR 머지되면 PR에서 만들어진 권한 상수를 사용하여 개선해주세요~

**Comment by SWARVY** [comment]
해당 작업 #221 작업에서 완료되어 close 처리 하도록 하겠습니다
